### ISSUE TITLE
[Feature Request] Automatic Join via JSON config.

### ISSUE THREAD

**Issue by teward** [SocraticPhoenix/TioBot#2]
If we follow #1, then we can also add in an autojoin feature that we can configure, such that the JSON store could have an element like this in it:

```
...,
'joins': { 'STACK_EXCHANGE': [2,3,4,...], 'STACK_OVERFLOW': [2,5,6,...], ...} ,
...
```

where the lists underneath the `joins` JSON is the room IDs for each 'site' we would connect to.

Then we just loop over the keys in the `joins` JSON, and issue a 'join' command for each individual room ID.

**Comment by SocraticPhoenix** [comment]
fixed
